# ======================================================================
# TURN OFF PROGRESS BAR TO MAKE SCRIPT RUN FASTER
# ======================================================================
$Global:progressPreference = 'silentlyContinue'

# ======================================================================
# SUPPRESS SIMPLE ERROR-MESSAGES GENERATED BY SCRIPT TO STAY ALIVE
# ======================================================================
$ErrorActionPreference = 'SilentlyContinue'

# ======================================================================
# Installing Chocolatey, Default PS-Profile, the Oh-My-Posh module,
# and adding themes and fonts.
# ======================================================================
Write-Host "Installing Oh My Posh!..."
irm https://github.com/ChrisTitusTech/powershell-profile/raw/main/setup.ps1 | iex
Write-Host "=================================="

# Installing zoxide needed for Posh and the code written in the Profile.
Write-Host "Installing Zoxide using Choco..."
choco install zoxide -y
Write-Host "O-M-P and Chocolatey installed..."
Write-Host "=================================="

# Overwriting the default PS-Profile with my personal modified version.
# Mark a <#> to the next command to skip this.
Write-Host "Pulling personal PS-Profile..."
irm "https://raw.githubusercontent.com/Masterkatt3n/new_boots/main/PowerShell-profile.ps1" | Set-Content -Path $PROFILE
Write-Host "Default profile overwritten by customized in Pwsh..."
Write-Host "=================================="

# Installing the PSWindowsupdate module to manage updates through PowerShell.
# Mark <#> to skip.
Write-Host "Installing PSWindowsUpdate Module..."
Install-Module PSWindowsUpdate -Force
Add-WUServiceManager -MicrosoftUpdate -Confirm:$false
Write-Host "PSWindowsUpdate installed..."
Write-Host "=================================="

# Finishing up by starting the WinUtil application for further installation/modifications.
Write-Host "WinUtil powering up..."
iwr -useb https://christitus.com/win | iex

# The End
